### ISSUE TITLE
Pipeline rather than the whole mess that our rendering system currently is?

### ISSUE THREAD

**Issue by josealvim** [uspgamedev/ugdk#127]
The case for Pipelines rather than the current rendering method we use:

We would divide things into:
1. Render OutStreams (Textures and Windows)
2. Render Pipelines (A vector of render functions with some other stuff)
3. Render InStreams (Like our canvas, a interface the user can send stuff to for rendering)

The benefits (I'll talk further about each in an attached file):

- More elegant, and overall, robust code.
- Clearer relations between classes and their uses.
- Simpler validity assertion.
- Easier to maintain.
- Simple way to dynamically set priority to render functions.
- Simple support for multi-layered rendering.
- Ability to render multiple functions onto the same Render OutStream.

**Comment by josealvim** [comment]
The way things currently are, we have Window, which is our buffer layer between ugdk and SDL, which has a raw pointer to a SDL_window,

When a dev wants to render something on-screen he'd have to create a canvas, (which is tied to the number of renderscreens in graphics::manager at the time of the call to Run() ) draw on that.


Wouldn't it be better if we had a system that:
- Was SLD_Window specific: meaning that if we closed the window it could easily be killed
- Allowed for multiple step rendering: Ground, shadows, sprites, and Then GUI
- Neatly organized 2 out of 3 of the basic classes of graphical rendering currently in use:
1. graphic::Canvas
2. desktop::Window

With pipelines, we could have the more intuitive graphic::RenderTarget

**Comment by josealvim** [comment]
- More elegant and robust
`  `As it is, we have a Canvas, RenderTarget, Window, etc. BUT You don't really 'draw' on the canvas, you pass stuff to it, in a render_function, and IT calls stuff accordingly in the RenderTarget it is associated to. 
`  `The problem is, those relations aren't fixed at all, today, if you close a window you have to be careful not to mix up the render_functions, and you have to delete the RenderScreens yourself. It's way more complicated to understand and to develop with.

- Clearer relations between classes and their uses
`  `As it is, we have a graphic::Canvas, which is created every render cycle, for every graphic::RenderScreen, which is just a graphic::RenderTarget, which is tied to a desktop::Window, which knows of a SDL_Window by a pointer.
`  `Every such Canvas is sent to a render_function (AKA function<void(canvas&)>) that is stored in the current action::Scene. What all of this does is, it takes what we want to render to, wraps it around a canvas and gives it to a function that will act on it.
`  `The problem with that is, the way the code has been written (partially my fault) leaves very little room for freedom.

- Simpler validity assertion
`  `If the Pipeline had a weak_ptr to its RenderTarget, when it tried to lock(), it would fail, if the Window was closed. By concentrating the render_functions relevant to _a_ window or texture _in_ a single (well potentially multiple, but ignore that) object with a weak_ptr to it, when we unregister the Window (eg.)  it will invalidate the shared_ptr and and the Pipeline won't even run.
`  `Since the Pipeline only has the render functions that would output to the Target, this means no mixing up of functions is even _possible_.

- Easier to maintain
`  `Okay, this is personal, but I think the way we've coded so far has lead to some freakish looking structures and every time we want to add a feature we need to understand a Bunch of seemingly unrelated code, just look at how rendering works atm (ProfileSection "render").

- Simple way to dynamically set priority to render functions
`  `Pipelines can have associated priorities, that is, an int that establishes in what order the engine should run the Pipelines associated to a Window.

- Simple support for multi-layered rendering
`  `A Pipeline would run a vector of render_functions in order, which means if you had a dedicated ground rendering_function, then a dedicated entity-sprite render_function and a HUD function. It'd run in order and it would naturally encapsulate the idea multi-layering.

- Ability to render multiple functions onto the same Render OutStream
`  `Right now, that's a pain, but with Pipelines, we could just set and forget.

**Comment by henriquegemignani** [comment]
Seems reasonable. But:

1. I'm not exactly sure what's a Render OutStream and a Render InStream and what's the difference.

2. Prototype! Write an end user example, even if non-functional (because the APIs does not exist yet), to see if the end user code is reasonable.

3. Would you just store a bunch of render functions to be called later right? Be sure to not break complex flow like:
    1. Set shader A
    2. Render Rect 1 with Texture X
    3. Bind Texture Z for RTT
    4. Render Rect 2 with Texture Y
    5. Set shader B
    6. Render Rect 1 with Texture Y
    7. Stop rendering to Z
    8. Set shader C
    9. Render Rect 2 with Texture Z

**Comment by josealvim** [comment]
I have to think about 3., but I'll get on doing 2. ASAP.
As for 1.:
Render OutStream is just a bad temporary name for the place we pump the end result of a Pipeline, it will probably be much like the RenderTarget class. Inherit it and implement it. This makes the relationship with desktop::Window more straightforward: Maybe we should even make the Window class a children of RenderTarget, rather than using the RenderScreen class.

Render InStream would look like Canavs, which interfaces the Windows and render_functions.

**Comment by josealvim** [comment]
Alright, I don't understand the system nearly enough to undertake this at the moment.
Implementing this would mean a complete overhaul, which while I could do, give enough time and shoulders to cry over, may not be the best use of my time at this juncture.

**Comment by josealvim** [comment]
I'm going to try my hand at it, but help is WANTED

**Comment by josealvim** [comment]
From what I and Kazuo talked, I think it is best to wait til' we separate the rendering from the scene.

When that's done:

We'll assume our windows are SDL windows, and we will deal with 2 types of RenderTargets, a WindowViewport, which is better than screen since we can have multiple viewports per SDL_Window, and the good old RenderTextures.

Pipelines are going to be partially ordered by dependency and when rendering the scene, we run them in order of dependency.

For ease of mind, we will have desktop::Windows and our graphic::Viewports talk to each other, so that deletion and validity are made safe and simple.

Furthermore, move to use unique IDs to refer to our stuff so that deleting them from vectors and the like wont' be such a pain.

**Comment by josealvim** [comment]
@henriquegemignani 
Regarding 3.
Since we are going to be passing lambdas to our rendersteps, which is what we did before but under the guise of render_function, setting the current shader or binding a texture shouldn't be any harder. I reckon the lambda would capture those things, right?

Basically, we'd:

add a Pipeline() with ID to the scene,
`auto &ourscene = GET-OUR-SCENE;`
`ourscene.AddPipeline("main_line");`
`auto &main_line = ourscene.Pipeline("main_line"); //let's call it main_line`

add a render_step to it:
`main_line.set_render_step(0, [...](Canvas& canvas) {`
`SetShader(A); Render r_1 with tex_x;`
`SetShader(C); Render r_2 with tex_z;`
`});`

Add another Pipeline
`ourscene.AddPipeline("aux_texture_z_line");`
`auto &aux_line = ourscene.Pipeline("aux_texture_z_line"); //let's call it aux_line`

add a render_step to it:
`aux_line.set_render_step(0, [...](Canvas& canvas) {`
`SetShader(A);`
`Bind(Z) for RTT;`
`Render r_2 with tex_y;`
`SetShader(B);`
`Render r_1 with tex_y;`
`Stop the RTT to Z`
`});`

we then add a dependency to the main_line Pipeline
`main_line.add_dependency(aux_line);`

I think you can always solve the dependency order, I mean, you can't require something that requires you to do something as well, so there should always be a way to unwrap the complicated stuff.

**Comment by henriquegemignani** [comment]
What's the use of assuming that each Window has an SDL_Window associated?

**Comment by josealvim** [comment]
Wil and I started discussing if this idea was actually any good or not. The main problem with it was Ogre, which is huge and doesn't (of course) follow our standard of code. Which means we either wrap Ogre so we can treat it as a part of UGDK, or we can assume we only deal with SDL_Windows and if the dev-user wants to use Ogre, he needs to code it with Ogre itself.

As is, our desktop::Windows ALREADY have a raw pointer to a SDL_Window. So, dedicating ourselves to SDL seemed the most reasonable idea, since this _is_ the ugdk-_core_ module not ugdk-_3d_ module.
