### ISSUE TITLE
It is not clear that pyramidworks::collision::CollisionObject steals Shape ownership.

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/ugdk#27]
You can only find it out if you look at the attribute's type.

I suggest adding a note to the documentation, or changing the constructor's parameter type to "unique_ptr<Shape>&&".

**Comment by henriquegemignani** [comment]
Missing documentation seems to be an oversight: I though it was documented.

Changing the parameter type to "unique_ptr&&" is problematic regarding to
SWIG, considering only SWIG 3.0 supports r-value references, and I'm not
really sure how it handles unique_ptr.

## 

Henrique Gemignani Passos Lima
http://uspgamedev.org/

2014-08-13 17:54 GMT-03:00 Wilson Kazuo Mizutani notifications@github.com:
