### ISSUE TITLE
Avoid #ifdefs in engine.cc

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/ugdk#40]
Is there a way to do this? Since there is no actual class Engine, perhaps we could use multiple implementation source files? It is pretty much the same, but at least the readability improves.

**Comment by henriquegemignani** [comment]
This should be done avoiding replicating the same code in both files. Considering the way engine.cc currently works, this will require significant refactoring. I don't plan on doing this myself.

**Comment by Kazuo256** [comment]
For now, I'm more interested in finding out the best way to do this, specially since it is going to be a lot of work. Don't want to regret it again too soon XD.
