### ISSUE TITLE
Travis is stuck on Ubuntu 12.04

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/ugdk#47]
Since we want to update dependencies (#43) that might be a problem.

Is there a way to circumvent this?

Problem in question: https://travis-ci.org/uspgamedev/ugdk/jobs/223678666 (we wanted to upgrade the cmake version used to 3+)

**Comment by henriquegemignani** [comment]
There's an Ubuntu 14.04 image on Travis. Not sure exactly how to use it.

Em 19 de abr de 2017 10:20 PM, "Wilson Kazuo Mizutani" <
notifications@github.com> escreveu:

**Comment by Kazuo256** [comment]
Tried to use the 14.04 image, [result](https://travis-ci.org/uspgamedev/ugdk/jobs/225301513).

**Comment by Kazuo256** [comment]
We actually really need this because Ubuntu 12.04 cannot compile c++14!!!
