### ISSUE TITLE
VirtualObj-Lua: value<string> causes segfault

### ISSUE THREAD

**Issue by henriquegemignani** [uspgamedev/ugdk#6]
The VirtualObj::value<string> function causes a segmentation fault when the associated data is a Lua VirtualData is a type that isn't convertible to string.

The expected behavior is to either throw an exception or to return an empty string.

**Comment by Kazuo256** [comment]
Please check if 66976dd7b6ae11b994e1d11f33658b261ba90993 fixes the problem.

**Comment by Kazuo256** [comment]
Never mind that. Check if cbd7f9ef3343b850019a7d3ca9bdf7a59001d527 solves it.

(forgot to actually use the code I wrote)
