### ISSUE TITLE
There are still references to spritetype

### ISSUE THREAD

**Issue by rubens-bolgheroni** [uspgamedev/ugdk#61]
I was looking at the code we were dealing with on monday, and I noticed that there's still some references to spritetypes on the json2spriteanimation.h, despite its name change. I think this can generate possible error or confusion in the future

**Comment by Kazuo256** [comment]
Indeed, although it is only a macro name. I'm adding it to the milestone.

**Comment by rubens-bolgheroni** [comment]
Ok, I didn't know what if it would have an effect at all, but better being safe than sorry, haha.
